// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJ904JAcZG7OeVl51S8e3YVM-gyhiuR4',
    appId: '1:453256167677:web:ece64a62e63414839f3e94',
    messagingSenderId: '453256167677',
    projectId: 'riky-ripaldo',
    authDomain: 'riky-ripaldo.firebaseapp.com',
    databaseURL: 'https://riky-ripaldo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riky-ripaldo.appspot.com',
    measurementId: 'G-ELMJ9CFFEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLjkTWFZZP7I-W7f2v42gKbL_gI9M6JsM',
    appId: '1:453256167677:android:ccf8e419f452042b9f3e94',
    messagingSenderId: '453256167677',
    projectId: 'riky-ripaldo',
    databaseURL: 'https://riky-ripaldo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riky-ripaldo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCId450Oetp3lE7msWaip-7flcb9EtgnF0',
    appId: '1:453256167677:ios:a5ab8d42abd9fc109f3e94',
    messagingSenderId: '453256167677',
    projectId: 'riky-ripaldo',
    databaseURL: 'https://riky-ripaldo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riky-ripaldo.appspot.com',
    androidClientId: '453256167677-1k9p18pp6soslmn3bs3uodu5hvur9at4.apps.googleusercontent.com',
    iosClientId: '453256167677-ei4fkl6de93420p57abmviggu1vkr3lp.apps.googleusercontent.com',
    iosBundleId: 'id.rikyripaldo.chatku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCId450Oetp3lE7msWaip-7flcb9EtgnF0',
    appId: '1:453256167677:ios:a5ab8d42abd9fc109f3e94',
    messagingSenderId: '453256167677',
    projectId: 'riky-ripaldo',
    databaseURL: 'https://riky-ripaldo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riky-ripaldo.appspot.com',
    androidClientId: '453256167677-1k9p18pp6soslmn3bs3uodu5hvur9at4.apps.googleusercontent.com',
    iosClientId: '453256167677-ei4fkl6de93420p57abmviggu1vkr3lp.apps.googleusercontent.com',
    iosBundleId: 'id.rikyripaldo.chatku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJ904JAcZG7OeVl51S8e3YVM-gyhiuR4',
    appId: '1:453256167677:web:cb21e0a375ec04179f3e94',
    messagingSenderId: '453256167677',
    projectId: 'riky-ripaldo',
    authDomain: 'riky-ripaldo.firebaseapp.com',
    databaseURL: 'https://riky-ripaldo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riky-ripaldo.appspot.com',
    measurementId: 'G-RVXRCRTW8T',
  );
}
